apiVersion: v1
kind: Service
metadata:
  name: ai-recommendation-service
  namespace: ecommerce
  labels:
    app: ai-recommendation-service
spec:
  type: ClusterIP
  selector:
    app: ai-recommendation-service
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
