server:
  port: 8088

spring:
  application:
    name: search-service
  config:
    import: optional:configserver:http://localhost:8888
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis_secret}
  cache:
    type: redis

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
