apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: ecommerce
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
