server:
  port: 8084

spring:
  application:
    name: inventory-service
  config:
    import: optional:configserver:http://localhost:8888
  cassandra:
    keyspace-name: ${CASSANDRA_KEYSPACE:ecommerce_inventory}
    contact-points: ${CASSANDRA_HOST:localhost}
    port: ${CASSANDRA_PORT:9042}
    local-datacenter: ${CASSANDRA_DC:datacenter1}
    schema-action: CREATE_IF_NOT_EXISTS
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis_secret}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
