server:
  port: 8088

spring:
  application:
    name: search-service
  threads:
    virtual:
      enabled: true
  elasticsearch:
    uris: http://elasticsearch:9200
    username: ${ELASTICSEARCH_USERNAME:elastic}
    password: ${ELASTICSEARCH_PASSWORD:elastic_secret}
    connection-timeout: 5s
    socket-timeout: 30s
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD:redis_secret}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 1.0
