input {
  tcp {
    port => 5000
    codec => json_lines
  }
  udp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [logger_name] {
    mutate {
      add_field => { "service" => "%{[app_name]}" }
    }
  }

  if [stack_trace] {
    mutate {
      add_tag => ["stacktrace"]
    }
  }

  mutate {
    remove_field => ["@version", "host", "port"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "ecommerce-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
